# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lakshmi-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4677f17439b7478f80f70bce7ccd31dc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9e7236f9627c4c6085b56e5d9cc150a4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4677f17439b7478f80f70bce7ccd31dc }}/blogtracker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lakshmi-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0cf11c5bde447a5aaaa85ba7ac58396 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4677f17439b7478f80f70bce7ccd31dc }}/blogtracker:${{ github.sha }}'